// SPDX-FileCopyrightText: 2026 atyxeut <atyxeut@outlook.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

export module fmia.math.sequence.smooth_number;

import std;

import fmia.meta;

export namespace fmia {

// the behavior is undefined if the given prime list is not valid
template <std::integral Result, std::integral T, std::ranges::random_access_range R>
  requires std::integral<std::ranges::range_value_t<R>>
[[nodiscard]] constexpr std::vector<Result> smooth_number_list(T count, R&& primes) pre(count > 0) {
  std::vector<Result> ans;
  ans.reserve(count);
  ans.emplace_back(1);

  const auto n = std::ranges::size(primes);

  // aux[i].first: candidate for the ith smooth_number, generated by primes[i]
  // aux[i].second: index of the next factor to generate a candidate with the ith prime
  std::vector<std::pair<Result, T>> aux;
  aux.reserve(n);
  for (auto prime : primes)
    aux.emplace_back(std::move(prime), 0);

  for (T i = 1; i < count; ++i) {
    Result num = std::numeric_limits<Result>::max();
    for (const auto& [cand, _] : aux)
      num = std::min(num, cand);
    ans.emplace_back(num);
    for (auto j = 0uz; auto& [cand, idx] : aux) {
      if (cand == num) {
        ++idx;
        cand = ans[idx] * primes[j];
      }
      ++j;
    }
  }

  return ans;
}

} // export namespace fmia
